### ISSUE TITLE
GeoIpService Exception 

### ISSUE THREAD

**Issue by AdmiralSG** [cravler/CravlerMaxMindGeoIpBundle#14]
Hello. I am having an exception throw trying to execute my website. Debbuging this, an exception parameter type appears:

return $this->services['cravler_max_mind_geo_ip.service.geo_ip_service'] = new \Cravler\MaxMindGeoIpBundle\Service\GeoIpService($this);

But symfony says that this method expects an array as parameter, but $this is an object.

Here you have my configs (using symfony 2.8.49):

- Composer.json:

"require" : {
		"php" : ">=5.3.9",
		"symfony/symfony" : "2.8.*",
		"doctrine/orm" : "^2.4.8",
		"doctrine/doctrine-bundle" : "~1.4",
		"symfony/swiftmailer-bundle" : "~2.3",
		"symfony/monolog-bundle" : "~2.4",
		"sensio/distribution-bundle" : "~5.0",
		"sensio/framework-extra-bundle" : "^3.0.2",
		"incenteev/composer-parameter-handler" : "~2.0",
		"besimple/i18n-routing-bundle": "^2.3",
		"paypal/rest-api-sdk-php": "^1.13",
		"stripe/stripe-php": "^6.10",
		"cravler/maxmind-geoip-bundle": "1.2.1" (we also tried dev-master)
	},

For further information, keep me informed.
I hope you can help me with this error, please.

Thank you!

**Comment by cravler** [comment]
looks like cache issue
