### ISSUE TITLE
cravler:maxmind:geoip-update not working on windows

### ISSUE THREAD

**Issue by Seb33300** [cravler/CravlerMaxMindGeoIpBundle#20]
When running the command `cravler:maxmind:geoip-update` on Windows:

> Invalid argument, `C:/Path/To/Temp/max99BF.tmp.tar` cannot be found

In my temp folder and I am able to find 2 files:
```
max99BF.tar
max99BF.tmp.tar.gz
```

It looks like the `PharData::decompress` method generates a `max99BF.tar` file instead of `max99BF.tmp.tar`.

Am I the only one to encounter this issue?
I am using PHP 7.1 on Windows 10.

**Comment by cravler** [comment]
I am not using windows, if you find the issue, you can make PR
