### ISSUE TITLE
Composer script handler doesn't work with Symfony 3

### ISSUE THREAD

**Issue by QuingKhaos** [cravler/CravlerMaxMindGeoIpBundle#6]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Version used | v1.1.1 |
#### Actual Behavior

The composer script handler wants to execute `app/console`, which doesn't exist.
#### Expected Behavior

The composer script handler should detect the new Symfony 3 directory layout and execute `bin/console` if detected. Btw. the Symfony 3 directory layout is also doable with Symfony 2.
#### Possible Solutions

Detect the `symfony-bin-dir` composer extra config, to know where to search for the console. Fall back to `symfony-app-directory` if not found.

Pull request will follow (:

**Comment by cravler** [comment]
fixed: v1.2.0
