### ISSUE TITLE
Add support for Symfony 4.

### ISSUE THREAD

**Issue by Ne-Lexa** [cravler/CravlerMaxMindGeoIpBundle#9]
Please add support for Symfony 4 and, if possible, a recipe for Symfony Flex.

Now in `composer.json`:
```json
"require": {
        ...
        "symfony/framework-bundle": "~2.3|~3.0",
        ...
}
```

**Comment by bpolaszek** [comment]
Hello @Ne-Lexa,

Support for Symfony 4 has been added to dev-master with #10.

But @cravler, something still doesn't work as expected:

Despite no error is shown when installing the bundle with Symfony 4, the `cravler:maxmind:geoip-update` command is not discovered by the framework, and I don't know why. It's OK with Symfony 3.

I have open an issue on Stackoverflow to know more about that.

https://stackoverflow.com/questions/49134340/symfony-4-3rd-party-bundle-commands-are-no-longer-automatically-discovered

Do you have any clue?

**Comment by cravler** [comment]
fix in dev-master

**Comment by bpolaszek** [comment]
I'm pretty sure this was not the solution, commands should be discovered without explicitly defining them. 

Other bundles behave that way, and I'm sure the reason it didn't work here is a misconfiguration somewhere... 

It just drives me crazy not to figure out what!

**Comment by bpolaszek** [comment]
My bad, didn't see that: https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md#httpkernel

The Symfony 4+ documentation about commands is not up to date then, I will report that.

**Comment by bpolaszek** [comment]
@cravler It works well on Symfony 4 :)
Can you please tag a new release?

**Comment by cravler** [comment]
v1.2.0

**Comment by bpolaszek** [comment]
Thanks @cravler.

**Comment by aosow** [comment]
Hi @cravler, i use your package in SF4. 
here is the exception i got 'An account ID and license key are required to use this service.'
